name: EasyFeedback
main: io.github.matiasilva.easyfeedback.EasyFeedback
version: 1.0
api-version: 1.15
author: hamlam
commands:
  feedback:
    description: Mostra o link para o nosso canal de Slack!
    usage: "Utiliza /feedback <escreve o que quiseres aqui>"
permissions:
  EasyFeedback.feedback.read:
    description: Allows users to read feedback
  EasyFeedback.feedback.write:
    description: Allows users to write feedback